name: Deep Q-Learning Test
problem: "problems/wscc-9-9.json"
model: {}
trainer: !NaiveClassic
  replay:
    capacity: 2000
    init: 200
    minibatch: 1
  lr: 0.0001
  epsilon: 0.25
  discount: 0.9
  target_update_period: 50
