[package]
name = "dmscli"
version = "0.1.0"
edition = "2021"
authors = ["İlker Işık <iiilker99@gmail.com>"]
description = "CLI for the disaster management system."

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
dmslib = { path = "../dmslib" }
serde_json = "1.0"
